FROM node:20-alpine

# Install prerequisites
RUN apk update && apk add --no-cache git python3 youtube-dl

# Install global npm packages
RUN npm install -g @unblockneteasemusic/server NeteaseCloudMusicApi

# Install yt-dlp
RUN wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp &&     chmod +x /usr/local/bin/yt-dlp

# Copy entrypoint script
COPY docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh

# Set environment variables
ENV NODE_TLS_REJECT_UNAUTHORIZED=0

# Define entrypoint and default command
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["npx", "NeteaseCloudMusicApi"]
