/* auto-generated by NAPI-RS */
/* eslint-disable */
/** 关闭 Discord RPC */
export declare function disableDiscordRpc(): void

/**
 * 禁用 SMTC
 *
 * ### Errors
 *
 * 会在调用 Windows API 失败时抛出错误，一般都是系统版本过低的原因
 */
export declare function disableSmtc(): void

/** Discord RPC 的配置内容 */
export interface DiscordConfigPayload {
  /**
   * 是否要在暂停后也显示 Discord Activity，如果为 false，则在暂停后清空 Discord Activity
   *
   * ### 备注
   *
   * 开启此功能后，暂停时进度条将显示为 0 (因为是通过 Hack 实现的)
   */
  showWhenPaused: boolean
  /**
   * 自定义 "Listening to" 后面应该显示什么
   *
   * 详情请查看 [`DiscordDisplayMode`]
   */
  displayMode?: DiscordDisplayMode
}

/** 自定义 Discord Activity 中 "Listening to" 后面应该显示什么 */
export declare enum DiscordDisplayMode {
  /** 显示为 "Listening to Spotify" */
  Name = 0,
  /** 显示为 "Listening to Rick Astley" */
  State = 1,
  /** 显示为 "Listening to Never Gonna Give You Up" */
  Details = 2
}

/**
 * 启用 Discord RPC
 *
 * ### 备注
 *
 * 启用后会立刻尝试连接，如果 Discord 未启动，或因为其他未知原因连接失败，会每 5 秒尝试连接一次
 */
export declare function enableDiscordRpc(): void

/**
 * 启用 SMTC
 *
 * ### Errors
 *
 * 会在调用 Windows API 失败时抛出错误，一般都是系统版本过低的原因
 */
export declare function enableSmtc(): void

/**
 * 初始化插件
 *
 * ### 参数
 *
 * * `log_dir` - 要把日志文件保存到的路径
 *
 * ### Errors
 *
 * 可能会在日志初始化失败，或者 SMTC 初始化失败时 (一般都是系统版本过低的原因) 抛出错误
 *
 * ### 备注
 *
 * 如果其他 Windows API 调用失败，则只会打印日志并静默失败
 */
export declare function initialize(logDir: string): void

export interface MetadataParam {
  songName: string
  authorName: string
  albumName: string
  /** 只用于 SMTC 更新 */
  coverData?: Buffer
  /** 只用于 Discord RPC 更新，因为 Discord RPC 只能上传封面链接 */
  originalCoverUrl?: string
  /** 会以 "NCM-{ID}" 的格式上传到 SMTC 的 “流派” 字段 */
  ncmId?: number
  /**
   * 单位是毫秒
   *
   * 只用于 Discord RPC，因为 Discord RPC 不太支持只更新元数据而不更新进度信息
   */
  duration?: number
}

export declare enum PlaybackStatus {
  Playing = 0,
  Paused = 1
}

export interface PlayModePayload {
  isShuffling: boolean
  repeatMode: RepeatMode
}

export interface PlayStatePayload {
  status: PlaybackStatus
}

/**
 * 注册 SMTC 事件回调 (上一首、下一首、暂停、播放等)
 *
 * ### 参数
 *
 * `(event: SmtcEvent) => void`
 *
 * ### Errors
 *
 * 如果 N-API 创建线程安全函数失败，会抛出错误。通常不应该发生，除非 JS 环境已经销毁了
 */
export declare function registerEventHandler(callback: (arg: SmtcEvent) => void): void

export declare enum RepeatMode {
  None = 0,
  Track = 1,
  List = 2
}

/** 关闭插件，清理资源 */
export declare function shutdown(): void

export interface SmtcEvent {
  type: SmtcEventType
  positionMs?: number
}

export declare enum SmtcEventType {
  Play = 0,
  Pause = 1,
  Stop = 2,
  NextSong = 3,
  PreviousSong = 4,
  ToggleShuffle = 5,
  ToggleRepeat = 6,
  Seek = 7
}

export interface TimelinePayload {
  /** 单位是毫秒 */
  currentTime: number
  /** 单位是毫秒 */
  totalTime: number
}

/**
 * 更新 Discord RPC 的配置
 *
 * ### 参数
 *
 * * `payload` - 配置信息，可以配置是否在暂停后也显示 Discord Activity 和 状态显示风格。详情请查看 [`DiscordConfigPayload`]
 */
export declare function updateDiscordConfig(payload: DiscordConfigPayload): void

/**
 * 更新歌曲元数据
 *
 * 同时也会更新 Discord 的元数据 (如果启用了 Discord RPC)
 *
 * ### 备注
 *
 * 更新 Discord RPC 的元数据时，必须提供 `original_cover_url`
 */
export declare function updateMetadata(payload: MetadataParam): void

/**
 * 更新播放模式
 *
 * ### 备注
 *
 * 只会更新 SMTC 的信息
 */
export declare function updatePlayMode(payload: PlayModePayload): void

/**
 * 更新播放状态 (播放/暂停)
 *
 * 同时也会更新 Discord 的播放状态 (如果启用了 Discord RPC)
 */
export declare function updatePlayState(payload: PlayStatePayload): void

/**
 * 更新进度信息
 *
 * 同时也会更新 Discord 的进度信息 (如果启用了 Discord RPC)
 *
 * ### 备注
 *
 * Discord RPC 实现的进度更新有节流，调用此函数无需担心 Discord RPC 的速率限制
 */
export declare function updateTimeline(payload: TimelinePayload): void
