/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function cancelDownload(id: number): void

export declare function downloadFile(id: number, url: string, filePath: string, metadata: SongMetadata | undefined | null, onProgress: ((err: Error | null, arg: string) => any)): Promise<void>

export declare function getTaskbarCreatedMessageId(): number

export interface SongMetadata {
  title: string
  artist: string
  album: string
  coverUrl?: string
  lyric?: string
  description?: string
}

export declare function writeMusicMetadata(filePath: string, metadata: SongMetadata, coverPath?: string | undefined | null): void
